# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

# trigger:
# - master

# pool:
#   vmImage: 'ubuntu-16.04'
# strategy:
#   matrix:
#     # node_8_x:
#     #   node_version: 8.x
#     # node_9_x:
#     #   node_version: 9.x
#     node_12_x:
#       node_version: 12.x

# steps:
# - task: NodeTool@0
#   inputs:
#     versionSpec: '12.x'
#   displayName: 'Install Node.js'

# - script: |
#     pushd PopPopPotholes-Frontend
#     npm install 
#     npm install -g @angular/cli
#     ng build --prod
#     popd
#   displayName: 'npm install and build'

# - script: |
#     pushd PopPopPotholes-Frontend
#     ng add @azure/ng-deploy
#     deploy
#     popd
#   displayName: 'Deploy to Azure'
